#pragma once

#define AUDIO_SAMPLE_RATE_HZ          48000U
#define AUDIO_BYTES_PER_SAMPLE        2U
#define AUDIO_BITS_PER_SAMPLE         (AUDIO_BYTES_PER_SAMPLE * 8U)

#define AUDIO_SPK_CHANNELS            2U
#define AUDIO_MIC_CHANNELS            1U
#define AUDIO_I2S_CHANNELS            2U

#define AUDIO_SPK_BYTES_PER_FRAME     (AUDIO_SPK_CHANNELS * AUDIO_BYTES_PER_SAMPLE)
#define AUDIO_MIC_BYTES_PER_FRAME     (AUDIO_MIC_CHANNELS * AUDIO_BYTES_PER_SAMPLE)
#define AUDIO_I2S_BYTES_PER_FRAME     (AUDIO_I2S_CHANNELS * AUDIO_BYTES_PER_SAMPLE)

#define AUDIO_SPK_BYTES_PER_MS        ((AUDIO_SAMPLE_RATE_HZ / 1000U) * AUDIO_SPK_BYTES_PER_FRAME)
#define AUDIO_MIC_BYTES_PER_MS        ((AUDIO_SAMPLE_RATE_HZ / 1000U) * AUDIO_MIC_BYTES_PER_FRAME)
#define AUDIO_I2S_BYTES_PER_MS        ((AUDIO_SAMPLE_RATE_HZ / 1000U) * AUDIO_I2S_BYTES_PER_FRAME)

#define AUDIO_SPK_TARGET_MS           5U
#define AUDIO_SPK_BUFFER_MS           (AUDIO_SPK_TARGET_MS * 2U)
#define AUDIO_SPK_BUFFER_BYTES        (AUDIO_SPK_BUFFER_MS * AUDIO_SPK_BYTES_PER_MS)
#define AUDIO_SPK_TARGET_BYTES        (AUDIO_SPK_TARGET_MS * AUDIO_SPK_BYTES_PER_MS)

#define AUDIO_MIC_BUFFER_MS           10U
#define AUDIO_MIC_BUFFER_BYTES        (AUDIO_MIC_BUFFER_MS * AUDIO_MIC_BYTES_PER_MS)

#define AUDIO_PROP_PACKET_MS          1U
#define AUDIO_I2S_BLOCKS_PER_MS       2U
#define AUDIO_I2S_BLOCK_BYTES         (AUDIO_I2S_BYTES_PER_MS / AUDIO_I2S_BLOCKS_PER_MS)
#define AUDIO_I2S_SAMPLE_PAIRS_PER_BLOCK (AUDIO_I2S_BLOCK_BYTES / AUDIO_I2S_BYTES_PER_FRAME)
