import os
import re
import sys
import shutil
from pathlib import Path


def restore_file(file_path, modified_content):
    """Write the modified content back to the file."""
    with open(file_path, 'w') as f:
        f.write(modified_content)
    print(f"Updated: {file_path}")

def process_cmake_file(file_path, context_name):
    """Process a CMake file with the given context name."""
    if not os.path.exists(file_path):
        print(f"Warning: {file_path} not found, skipping")
        return
        
    with open(file_path, 'r') as f:
        content = f.read()
    
    # Replace paths in the include directories
    content = re.sub(r'\$\{CMAKE_SOURCE_DIR\}/Core/', f'${{CMAKE_SOURCE_DIR}}/{context_name}/Core/', content)
    content = re.sub(r'\$\{CMAKE_SOURCE_DIR\}/\.\./', f'${{CMAKE_SOURCE_DIR}}/{context_name}/../', content)
    
    # Replace stm32cubemx library names
    content = re.sub(r'add_library\(stm32cubemx ', f'add_library(stm32cubemx_{context_name} ', content)
    content = re.sub(r'target_include_directories\(stm32cubemx ', f'target_include_directories(stm32cubemx_{context_name} ', content)
    content = re.sub(r'target_compile_definitions\(stm32cubemx ', f'target_compile_definitions(stm32cubemx_{context_name} ', content)
    content = re.sub(r'stm32cubemx\)', f'stm32cubemx_{context_name})', content)
    
    # Replace STM32_Drivers library names
    content = re.sub(r'add_library\(STM32_Drivers ', f'add_library(STM32_Drivers_{context_name} ', content)
    content = re.sub(r'target_sources\(STM32_Drivers ', f'target_sources(STM32_Drivers_{context_name} ', content)
    content = re.sub(r'target_link_libraries\(STM32_Drivers ', f'target_link_libraries(STM32_Drivers_{context_name} ', content)
    content = re.sub(r'set \(MX_LINK_LIBS \n    STM32_Drivers', f'set (MX_LINK_LIBS\n    STM32_Drivers_{context_name}', content)
        
    restore_file(file_path, content)

def restore_main_cmake(file_path):
    """Restore the main mx-generated.cmake file."""
    if not os.path.exists(file_path):
        print(f"Warning: {file_path} not found, skipping")
        return
        
    new_content = """# File automatically-generated by STM32CubeMX - Do not modify
set(ST_MULTICONTEXT BOOT_FLASH CACHE STRING "Type of multi-context")

#-----------------------Build Appli Project-----------------------#
if((${BUILD_CONTEXT} MATCHES .*Appli.*) OR (NOT DEFINED BUILD_CONTEXT))
message(" Build context: Appli")
# Add Appli project as a subdirectory
add_subdirectory(${PROJECT_SOURCE_DIR}/Appli ${CMAKE_SOURCE_DIR}/Appli/build)

# Define a build target for the Appli project
set(ST_BOOT_FLASH_APPLI_PROJECT_BUILD_TARGET ${CMAKE_SOURCE_DIR}/Appli/build/${CMAKE_PROJECT_NAME}_Appli${CMAKE_EXECUTABLE_SUFFIX_CXX} CACHE FILEPATH "Path to appli project target")
endif()


#-----------------------Build Appli Project-----------------------#
if((${BUILD_CONTEXT} MATCHES .*Boot.*) OR (NOT DEFINED BUILD_CONTEXT))
message(" Build context: Boot")
# Add Boot project as a subdirectory
add_subdirectory(${PROJECT_SOURCE_DIR}/Boot ${CMAKE_SOURCE_DIR}/Boot/build)

# Define a build target for the Boot project
set(ST_BOOT_FLASH_BOOT_PROJECT_BUILD_TARGET ${CMAKE_SOURCE_DIR}/Boot/build/${CMAKE_PROJECT_NAME}_Boot${CMAKE_EXECUTABLE_SUFFIX_CXX} CACHE FILEPATH "Path to boot project target")
endif()
"""
    
    restore_file(file_path, new_content)

    
def process_if_block_compiler_paths(file_path):
    """
    Process gcc-arm-none-eabi.cmake and add if(NOT DEFINED STM32_MCU_FLAGS) block when needed.
    Uses regex to find the compiler settings block and wrap it if not already wrapped.
    """
    if not os.path.exists(file_path):
        print(f"Warning: {file_path} not found, skipping")
        return
        
    with open(file_path, 'r') as f:
        content = f.read()
    
    # Define the compiler block pattern
    # This matches the entire block with any leading whitespace preserved
    compiler_block_pattern = re.compile(
        r'(\s*)(set\(\s*CMAKE_C_COMPILER\s+\$\{TOOLCHAIN_PREFIX\}gcc\)\s*\n'
        r'\s*set\(\s*CMAKE_ASM_COMPILER\s+\$\{CMAKE_C_COMPILER\}\)\s*\n'
        r'\s*set\(\s*CMAKE_CXX_COMPILER\s+\$\{TOOLCHAIN_PREFIX\}g\+\+\)\s*\n'
        r'\s*set\(\s*CMAKE_LINKER\s+\$\{TOOLCHAIN_PREFIX\}g\+\+\)\s*\n'
        r'\s*set\(\s*CMAKE_OBJCOPY\s+\$\{TOOLCHAIN_PREFIX\}objcopy\)\s*\n'
        r'\s*set\(\s*CMAKE_SIZE\s+\$\{TOOLCHAIN_PREFIX\}size\)\s*)', 
        re.MULTILINE
    )
    
    # Check if the block exists
    match = compiler_block_pattern.search(content)
    if not match:
        print("Info: Target block sequence not found in the input.")
        return
    
    # Get the block and its indentation
    indent = match.group(1)
    block = match.group(2)
    
    # Check if the block is already wrapped in if(NOT DEFINED STM32_MCU_FLAGS)
    # Look at what comes right before the block
    start_pos = match.start()
    preceding_lines = content[:start_pos].strip().split('\n')
    
    if preceding_lines and re.search(r'if\s*\(\s*not\s+defined\s+STM32_MCU_FLAGS\s*\)', preceding_lines[-1], re.IGNORECASE):
        print(f"Info: Found target block, but it seems already wrapped. Skipping wrapping.")
        return
    
    # Wrap the block with if(NOT DEFINED STM32_MCU_FLAGS)
    # Add 4 spaces to each line while preserving just one newline at the end
    indented_block = re.sub(r'(^|\n)(\s*)', r'\1\2' + '    ', block)
    
    # Just do one line break at the end
    indented_block = indented_block.rstrip(" ").rstrip("\n") + "\n"
    
    # Create the wrapped block with proper line breaks
    wrapped_block = f"{indent}if(NOT DEFINED STM32_MCU_FLAGS)\n{indented_block}endif()\n\n"
    
    # Replace the original block with the wrapped block
    new_content = content[:start_pos] + wrapped_block + content[match.end():]
    
    print("Info: Found target block and wrapped it.")
    restore_file(file_path, new_content)

def process_linker_path(file_path, context_name):
    """
    Process a CMake file with the given context name.
    Updates the STM32_LINKER_SCRIPT path to include the context name.
    """
    if not os.path.exists(file_path):
        print(f"Warning: {file_path} not found, skipping")
        return

    with open(file_path, 'r') as f:
        content = f.read()
    
    # Add the linker script pattern replacements
    # Match both patterns: set(STM32_LINKER_SCRIPT **/**.ld) and set(STM32_LINKER_SCRIPT **.ld)
    content = re.sub(r'set\s*\(\s*STM32_LINKER_SCRIPT\s+(?:[^/]+/)?([^/)]+\.ld)\s*\)', 
                     f'set(STM32_LINKER_SCRIPT {context_name}/\\1)', 
                     content)
    
    restore_file(file_path, content)

def process_linked_list_c(file_path):
    """
    Replace wrongly generated "HPDMA1_REQUEST_OCTOSPI1" with "HPDMA1_REQUEST_XSPI1"
    """
    if not os.path.exists(file_path):
        print(f"Warning: {file_path} not found, skipping")
        return

    with open(file_path, 'r') as f:
        content = f.read()
    
    content = re.sub(r'pNodeConfig.Init.Request = HPDMA1_REQUEST_OCTOSPI1;\n  pNodeConfig.Init.BlkHWRequest = DMA_BREQ_SINGLE_BURST;', 
                     f'pNodeConfig.Init.Request = HPDMA1_REQUEST_XSPI1;\n  pNodeConfig.Init.BlkHWRequest = DMA_BREQ_BLOCK;', 
                     content)
    
    restore_file(file_path, content)


def main():
    print("Starting...")
    
    # Process Appli and Boot CMake files
    process_cmake_file("../STM32_SW/Appli/mx-generated.cmake", "Appli")
    process_cmake_file("../STM32_SW/Boot/mx-generated.cmake", "Boot")
    
    # Verify and change Linker Paths
    process_linker_path("../STM32_SW/Appli/CMakeLists.txt", "Appli")
    process_linker_path("../STM32_SW/Boot/CMakeLists.txt", "Boot")
    
    # Verify and change the if(NOT DEFINED STM32_MCU_FLAGS) condition block
    process_if_block_compiler_paths("../STM32_SW/gcc-arm-none-eabi.cmake")
    
    # Replace wrongly generated "HPDMA1_REQUEST_OCTOSPI1" with "HPDMA1_REQUEST_XSPI1"
    process_linked_list_c("../STM32_SW/Appli/Core/Src/linked_list.c")
    process_linked_list_c("../STM32_SW/Boot/Core/Src/linked_list.c")
    
    # Restore the main CMake file
    restore_main_cmake("../STM32_SW/mx-generated.cmake")
        
    print("\nSuccessful!")

if __name__ == "__main__":
    main()