# File automatically-generated by STM32CubeMX - Do not modify
set(ST_MULTICONTEXT BOOT_FLASH CACHE STRING "Type of multi-context")

#-----------------------Build Appli Project-----------------------#
if((${BUILD_CONTEXT} MATCHES .*Appli.*) OR (NOT DEFINED BUILD_CONTEXT))
message(" Build context: Appli")
# Add Appli project as a subdirectory
add_subdirectory(${PROJECT_SOURCE_DIR}/Appli ${CMAKE_SOURCE_DIR}/Appli/build)

# Define a build target for the Appli project
set(ST_BOOT_FLASH_APPLI_PROJECT_BUILD_TARGET ${CMAKE_SOURCE_DIR}/Appli/build/${CMAKE_PROJECT_NAME}_Appli${CMAKE_EXECUTABLE_SUFFIX_CXX} CACHE FILEPATH "Path to appli project target")
endif()


#-----------------------Build Appli Project-----------------------#
if((${BUILD_CONTEXT} MATCHES .*Boot.*) OR (NOT DEFINED BUILD_CONTEXT))
message(" Build context: Boot")
# Add Boot project as a subdirectory
add_subdirectory(${PROJECT_SOURCE_DIR}/Boot ${CMAKE_SOURCE_DIR}/Boot/build)

# Define a build target for the Boot project
set(ST_BOOT_FLASH_BOOT_PROJECT_BUILD_TARGET ${CMAKE_SOURCE_DIR}/Boot/build/${CMAKE_PROJECT_NAME}_Boot${CMAKE_EXECUTABLE_SUFFIX_CXX} CACHE FILEPATH "Path to boot project target")
endif()
