/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v15.0
processor: RW612
package_id: RW612ETA2I
mcu_data: ksdk2_0
processor_version: 25.09.10
board: FRDM-RW612
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: 65c69a75-6687-4d60-9cba-6b87ca7b8e8d
  called_from_default_init: true
  selectedCore: cm33
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system'
- global_system_definitions:
  - user_definitions: ''
  - user_includes: ''
  - global_init: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'gpio_adapter_common'
- type_id: 'gpio_adapter_common'
- global_gpio_adapter_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'uart_cmsis_common'
- type_id: 'uart_cmsis_common'
- global_USART_CMSIS_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'gau_common'
- type_id: 'gau_common'
- global_gau_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
 * BOARD_InitPeripherals functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * DMA0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'DMA0'
- type: 'lpc_dma'
- mode: 'basic'
- custom_name_enabled: 'false'
- type_id: 'lpc_dma_2.5.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'DMA0'
- config_sets:
  - fsl_dma:
    - dma_table:
      - 0: []
    - dma_channels: []
    - init_interrupt: 'false'
    - dma_interrupt:
      - IRQn: 'DMA0_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void DMA0_init(void) {
} */

/***********************************************************************************************************************
 * NVIC initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'NVIC'
- type: 'nvic'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'nvic'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'NVIC'
- config_sets:
  - nvic:
    - interrupt_table:
      - 0: []
      - 1: []
    - interrupts:
      - 0:
        - channelId: 'SysTick'
        - interrupt_t:
          - IRQn: 'SysTick_IRQn'
          - enable_interrrupt: 'enabled'
          - enable_priority: 'false'
          - priority: '0'
          - enable_custom_name: 'false'
      - 1:
        - channelId: 'USB'
        - interrupt_t:
          - IRQn: 'USB_IRQn'
          - enable_interrrupt: 'enabled'
          - enable_priority: 'false'
          - priority: '0'
          - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void NVIC_init(void) {
} */

/***********************************************************************************************************************
 * GPIO initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'GPIO'
- type: 'lpc_gpio'
- mode: 'GPIO'
- custom_name_enabled: 'false'
- type_id: 'lpc_gpio_2.1.1'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'GPIO'
- config_sets:
  - lpc_gpio: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void GPIO_init(void) {
} */

/***********************************************************************************************************************
 * FLEXCOMM0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'FLEXCOMM0'
- type: 'flexcomm_i2s'
- mode: 'dma'
- custom_name_enabled: 'false'
- type_id: 'flexcomm_i2s_2.2.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'FLEXCOMM0'
- config_sets:
  - fsl_i2s:
    - i2s_config:
      - usage: 'playback'
      - masterSlave: 'kI2S_MasterSlaveNormalMaster'
      - sckPolM: 'false'
      - wsPolM: 'false'
      - pdmDataTx: 'false'
      - clockConfig:
        - sampleRate_Hz: 'kSAI_SampleRate48KHz'
        - clockSource: 'FXCOMFunctionClock'
        - clockSourceFreq: 'ClocksTool_DefaultInit'
        - masterClockDependency: 'true'
      - mode: 'kI2S_ModeI2sClassic'
      - dataLengthM: '16'
      - stereo: 'kSAI_Stereo'
      - i2s_mono_palcement: 'kSAI_Mono_Left'
      - positionM: '0'
      - secondary_channels_array: []
      - frameLengthM: '32'
      - rightLow: 'false'
      - leftJust: 'false'
      - watermarkM_Tx: 'ki2s_TxFifo4'
      - txEmptyZeroTx: 'true'
      - pack48: 'false'
  - dmaCfg:
    - dma_channels:
      - dma_tx_channel:
        - DMA_source: 'kDma0RequestFlexcomm0Tx'
        - init_channel_priority: 'false'
        - dma_priority: 'kDMA_ChannelPriority0'
        - enable_custom_name: 'false'
    - i2s_dma_handle:
      - enable_custom_name: 'false'
      - init_callback: 'true'
      - callback_fcn: 'I2S_TX_DMA_Callback'
      - user_data: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
/* Flexcomm I2S configuration */
const i2s_config_t FLEXCOMM0_config = {
  .masterSlave = kI2S_MasterSlaveNormalMaster,
  .mode = kI2S_ModeI2sClassic,
  .rightLow = false,
  .leftJust = false,
  .pdmData = false,
  .sckPol = false,
  .wsPol = false,
  .divider = 1,
  .oneChannel = false,
  .dataLength = 16,
  .frameLength = 32,
  .position = 0,
  .watermark = 4,
  .txEmptyZero = true,
  .pack48 = false
};
dma_handle_t FLEXCOMM0_TX_Handle;
i2s_dma_handle_t FLEXCOMM0_Tx_DMA_Handle;

static void FLEXCOMM0_init(void) {
  /* Flexcomm I2S initialization */
  I2S_TxInit(FLEXCOMM0_PERIPHERAL, &FLEXCOMM0_config);
  /* Enable the DMA 1 channel in the DMA */
  DMA_EnableChannel(FLEXCOMM0_TX_DMA_BASEADDR, FLEXCOMM0_TX_DMA_CHANNEL);
  /* Create the DMA FLEXCOMM0_TX_Handle handle */
  DMA_CreateHandle(&FLEXCOMM0_TX_Handle, FLEXCOMM0_TX_DMA_BASEADDR, FLEXCOMM0_TX_DMA_CHANNEL);
  /* Create the I2S DMA handle */
  I2S_TxTransferCreateHandleDMA(FLEXCOMM0_PERIPHERAL, &FLEXCOMM0_Tx_DMA_Handle, &FLEXCOMM0_TX_Handle, I2S_TX_DMA_Callback, NULL);
}

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
static void BOARD_InitPeripherals_CommonPostInit(void)
{
  /* Enable interrupt SYSTICK_IRQN request in the NVIC */
  EnableIRQ(SYSTICK_IRQN);
  /* Enable interrupt USB_IRQN request in the NVIC */
  EnableIRQ(USB_IRQN);
}

void BOARD_InitPeripherals(void)
{
  /* Global initialization */
  DMA_Init(DMA0_DMA_BASEADDR);

  /* Initialize components */
  FLEXCOMM0_init();
  /* Common post-initialization */
  BOARD_InitPeripherals_CommonPostInit();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
  BOARD_InitPeripherals();
}
