/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_dma.h"
#include "fsl_common.h"
#include "fsl_gpio.h"
#include "fsl_i2s.h"
#include "fsl_i2s_dma.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Used DMA device. */
#define DMA0_DMA_BASEADDR DMA0
/* NVIC interrupt vector ID (number). */
#define SYSTICK_IRQN SysTick_IRQn
/* NVIC interrupt handler identifier. */
#define SYSTICK_IRQHANDLER SysTick_Handler
/* NVIC interrupt vector ID (number). */
#define USB_IRQN USB_IRQn
/* NVIC interrupt handler identifier. */
#define USB_IRQHANDLER USB_IRQHandler
/* Definition of peripheral ID */
#define GPIO_GPIO GPIO
/* BOARD_InitPeripherals defines for FLEXCOMM0 */
/* Definition of peripheral ID */
#define FLEXCOMM0_PERIPHERAL ((I2S_Type *)FLEXCOMM0)
/* Definition of the clock source frequency */
#define FLEXCOMM0_CLOCK_SOURCE 1536000UL
/* Selected DMA channel number. */
#define FLEXCOMM0_TX_DMA_CHANNEL 1
/* Used DMA device. */
#define FLEXCOMM0_TX_DMA_BASEADDR DMA0

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const i2s_config_t FLEXCOMM0_config;
extern dma_handle_t FLEXCOMM0_TX_Handle;
extern i2s_dma_handle_t FLEXCOMM0_Tx_DMA_Handle;

/***********************************************************************************************************************
 * Callback functions
 **********************************************************************************************************************/
/* I2S DMA callback function for the FLEXCOMM0 component (init. function BOARD_InitPeripherals)*/
extern void I2S_TX_DMA_Callback(I2S_Type *,i2s_dma_handle_t *,status_t ,void *);

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
