#pragma once

enum {
	ITF_NUM_AUDIO_CONTROL = 0,
	ITF_NUM_AUDIO_STREAMING_SPK,
	ITF_NUM_AUDIO_STREAMING_MIC,
	ITF_NUM_CDC,
	ITF_NUM_CDC_DATA,
	ITF_NUM_TOTAL,
};

enum {
	STRID_LANGID = 0,
	STRID_MANUFACTURER,
	STRID_PRODUCT,
	STRID_SERIAL,
	STRID_UAC1,
	STRID_UAC2,
	STRID_CDC,
};

#define UAC2_ENTITY_CLOCK               0x04U
#define UAC2_ENTITY_SPK_INPUT_TERMINAL  0x01U
#define UAC2_ENTITY_SPK_FEATURE_UNIT    0x02U
#define UAC2_ENTITY_SPK_OUTPUT_TERMINAL 0x03U
#define UAC2_ENTITY_MIC_INPUT_TERMINAL  0x11U
#define UAC2_ENTITY_MIC_OUTPUT_TERMINAL 0x13U

#define UAC1_ENTITY_SPK_INPUT_TERMINAL  0x01U
#define UAC1_ENTITY_SPK_FEATURE_UNIT    0x02U
#define UAC1_ENTITY_SPK_OUTPUT_TERMINAL 0x03U
#define UAC1_ENTITY_MIC_INPUT_TERMINAL  0x11U
#define UAC1_ENTITY_MIC_OUTPUT_TERMINAL 0x13U
