
# Copyright 2025 NXP
#
# SPDX-License-Identifier: Apache-2.0


# Use clock_config.c from this projects folder
CONFIG_MCUX_PRJSEG_module.board.clock_customize_folder=y
CONFIG_MCUX_PRJSEG_module.board.pinmux_customize_folder=y
CONFIG_MCUX_PRJSEG_project.hw_app_customize_folder=y

# Enable debug console because its a dependency of the wifi driver
# However PRINTF will be redirected to log.c/log.h functions
CONFIG_MCUX_PRJSEG_module.board.console=y
CONFIG_MCUX_PRJSEG_module.board.console_lite=n
CONFIG_MCUX_PRJSEG_module.board.boardfile=n

# Enable DMA Driver
CONFIG_MCUX_COMPONENT_driver.lpc_dma=y

# Enable I2S DMA Driver
CONFIG_MCUX_COMPONENT_driver.flexcomm_i2s_dma=y

# Enables the offchip flash support
CONFIG_MCUX_COMPONENT_component.mflash_offchip=y

############################################################
# FreeRTOS related config
############################################################
# TODO: Check if needed and for duplicates with FreeRTOSConfig.h
CONFIG_MCUX_COMPONENT_middleware.freertos-kernel=y
CONFIG_MCUX_COMPONENT_middleware.freertos-kernel.heap_4=y
CONFIG_MCUX_COMPONENT_middleware.freertos-kernel.cm33_non_trustzone=y
# Enables NXP specific FreeRTOS extensions (often required by their drivers)
CONFIG_MCUX_COMPONENT_middleware.freertos-kernel.extension=y
# Tells the build system to use FreeRTOSConfig.h and not auto generate one
CONFIG_MCUX_PRJSEG_middleware.freertos-kernel.generated_config=n
# NXP Drivers use "OSA" (OS Abstraction) to talk to FreeRTOS.
CONFIG_MCUX_COMPONENT_component.osa=y
CONFIG_MCUX_COMPONENT_component.osa_free_rtos=y


############################################################
# Wi-Fi related config
############################################################
# Enables the Wi-Fi Middleware (WPL - Wireless Porting Layer)
CONFIG_MCUX_COMPONENT_middleware.edgefast_wifi_nxp=y
# This basically specifies IMU instead of SDIO
CONFIG_MCUX_DEPENDENCY_COMPONENT_middleware.wifi.wifidriver_DEPEND_ANYOF_OPTION_2=y
# Enables the configuration for specific Wi-Fi chip (Murata/AzureWave)
CONFIG_MCUX_COMPONENT_component.wifi_bt_module.config=y


CONFIG_MCUX_COMPONENT_driver.conn_fwloader=y
#CONFIG_MCUX_COMPONENT_driver.conn_fwloader.fw_bin=y